#######################################################################################
# Jekyll site settings
title: "Data, Inference, and Decisions"
author: "Data 102 Staff"

#######################################################################################
# New settings

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force


# Information about where the book exists on the web
repository:
  url: https://github.com/ds-102/ds-102-book  # Online location of your book
  path_to_book: ds-102-book  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)
  #
# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
